/**
 * String names for localization
 * An underscore converts to a period which causes nested object access
 * WARNING: You cannot have a key with name A and then have A_anything because it will not be able to create a nested object on a string
 * For consistency, the left side should match the right, give or take CamelCase on the left and snake case (e.g. common_blahBlah) on the right
 */
export enum StringNames {
  ChangePassword_ChangePasswordButton = 'changePassword_changePasswordButton',
  Common_ChangePassword = 'common_changePassword',
  Common_CurrentPassword = 'common_currentPassword',
  Common_Logo = 'common_logo',
  Common_NewPassword = 'common_newPassword',
  Common_ConfirmNewPassword = 'common_confirmNewPassword',
  Common_Dashboard = 'common_dashboard',
  Common_Loading = 'common_loading',
  Common_ReturnToKitchen = 'common_returnToKitchen',
  Common_Site = 'common_site',
  Common_StartCooking = 'common_startCooking',
  Common_Tagline = 'common_tagline',
  Common_Unauthorized = 'common_unauthorized',
  Common_UnexpectedError = 'common_unexpectedError',
  ForgotPassword_Title = 'forgotPassword_title',
  Game_ListSuccess = 'game_listSuccess',
  KeyFeatures_Title = 'keyFeatures_title',
  KeyFeatures_1 = 'keyFeatures_1',
  KeyFeatures_2 = 'keyFeatures_2',
  KeyFeatures_3 = 'keyFeatures_3',
  KeyFeatures_4 = 'keyFeatures_4',
  KeyFeatures_5 = 'keyFeatures_5',
  KeyFeatures_6 = 'keyFeatures_6',
  KeyFeatures_7 = 'keyFeatures_7',
  KeyFeatures_8 = 'keyFeatures_8',
  LanguageUpdate_Success = 'languageUpdate_success',
  Login_LoginButton = 'login_loginButton',
  LogoutButton = 'logoutButton',
  RegisterButton = 'registerButton',
  Splash_Description = 'splash_description',
  Splash_HowToPlay = 'splash_howToPlay',
  ValidationError = 'validationError',
  Validation_InvalidLanguage = 'validation_invalidLanguage',
  Validation_InvalidToken = 'validation_invalidToken',
  Validation_PasswordRegexError = 'validation_passwordRegexError',
  Validation_CurrentPasswordRequired = 'validation_currentPasswordRequired',
  Validation_PasswordsDifferent = 'validation_passwordsDifferent',
  Validation_NewPasswordRequired = 'validation_newPasswordRequired',
  Validation_PasswordMatch = 'validation_passwordMatch',
  Validation_ConfirmNewPassword = 'validation_confirmNewPassword',
}
