/**
 * String names for localization
 * An underscore converts to a period which causes nested object access
 * WARNING: You cannot have a key with name A and then have A_anything because it will not be able to create a nested object on a string
 * For consistency, the left side should match the right, give or take CamelCase on the left and snake case (e.g. common_blahBlah) on the right
 */
export enum StringNames {
  AccountError_Message = 'accountError_message',
  AccountError_Title = 'accountError_title',
  ChangePassword_ChangePasswordButton = 'changePassword_changePasswordButton',
  Common_ChangePassword = 'common_changePassword',
  Common_CurrentPassword = 'common_currentPassword',
  Common_Email = 'common_email',
  Common_GoToSplash = 'common_goToSplash',
  Common_Logo = 'common_logo',
  Common_NewPassword = 'common_newPassword',
  Common_ConfirmNewPassword = 'common_confirmNewPassword',
  Common_Dashboard = 'common_dashboard',
  Common_Loading = 'common_loading',
  Common_Password = 'common_password',
  Common_ReturnToKitchen = 'common_returnToKitchen',
  Common_Site = 'common_site',
  Common_StartCooking = 'common_startCooking',
  Common_Tagline = 'common_tagline',
  Common_Unauthorized = 'common_unauthorized',
  Common_UnexpectedError = 'common_unexpectedError',
  Common_Username = 'common_username',
  Error_AccountStatusIsDeleted = 'error_accountStatusIsDeleted',
  Error_AccountStatusIsLocked = 'error_accountStatusIsLocked',
  Error_AccountStatusIsPendingEmailVerification = 'error_accountStatusIsPendingEmailVerification',
  Dashboard_GamesCreated = 'dashboard_gamesCreated',
  Dashboard_GamesParticipating = 'dashboard_gamesParticipating',
  Dashboard_NoGames = 'dashboard_noGames',
  Dashboard_Title = 'dashboard_title',
  ForgotPassword_ForgotPassword = 'forgotPassword_forgotPassword',
  ForgotPassword_InvalidToken = 'forgotPassword_invalidToken',
  ForgotPassword_ResetPassword = 'forgotPassword_resetPassword',
  ForgotPassword_SendResetToken = 'forgotPassword_sendResetToken',
  ForgotPassword_Success = 'forgotPassword_success',
  ForgotPassword_Title = 'forgotPassword_title',
  Game_CreateGame = 'game_createGame',
  Game_CreateGameSuccess = 'game_createGameSuccess',
  Game_JoinGame = 'game_joinGame',
  Game_JoinGameSuccess = 'game_joinGameSuccess',
  Game_ListSuccess = 'game_listSuccess',
  KeyFeatures_Title = 'keyFeatures_title',
  KeyFeatures_1 = 'keyFeatures_1',
  KeyFeatures_2 = 'keyFeatures_2',
  KeyFeatures_3 = 'keyFeatures_3',
  KeyFeatures_4 = 'keyFeatures_4',
  KeyFeatures_5 = 'keyFeatures_5',
  KeyFeatures_6 = 'keyFeatures_6',
  KeyFeatures_7 = 'keyFeatures_7',
  KeyFeatures_8 = 'keyFeatures_8',
  LanguageUpdate_Success = 'languageUpdate_success',
  Login_LoginButton = 'login_loginButton',
  Login_Progress = 'login_progress',
  Login_ResentPasswordFailure = 'login_resentPasswordFailure',
  Login_ResentPasswordSuccess = 'login_resentPasswordSuccess',
  Login_Title = 'login_title',
  Login_UsernameOrEmailRequired = 'login_usernameOrEmailRequired',
  LogoutButton = 'logoutButton',
  RegisterButton = 'registerButton',
  Splash_Description = 'splash_description',
  Splash_HowToPlay = 'splash_howToPlay',
  ValidationError = 'validationError',
  Validation_InvalidEmail = 'validation_invalidEmail',
  Validation_InvalidLanguage = 'validation_invalidLanguage',
  Validation_InvalidTimezone = 'validation_invalidTimezone',
  Validation_InvalidToken = 'validation_invalidToken',
  Validation_PasswordRegexErrorTemplate = 'validation_passwordRegexErrorTemplate',
  Validation_CurrentPasswordRequired = 'validation_currentPasswordRequired',
  Validation_PasswordsDifferent = 'validation_passwordsDifferent',
  Validation_NewPasswordRequired = 'validation_newPasswordRequired',
  Validation_PasswordMatch = 'validation_passwordMatch',
  Validation_ConfirmNewPassword = 'validation_confirmNewPassword',
  Validation_Required = 'validation_required',
  Validation_UsernameRegexErrorTemplate = 'validation_usernameRegexErrorTemplate',
}
