services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    env_file:
      - .env
    network_mode: host
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./Mongo.Dockerfile
    container_name: db          # Ensures the container name is 'db'
    hostname: db                 # Sets the internal hostname to 'db'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME} 
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_REPLICA_SET_NAME=${MONGO_REPLICA_SET_NAME}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_KEYFILE=${MONGO_KEYFILE}
      - MONGO_DB_PATH=${MONGO_DB_PATH}
      - DB_HOST=127.0.0.1:27017
    network_mode: host

volumes:
  mongodb-data: