version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      NODE_ENV: development
      FONTAWESOME_KEY: ${FONTAWESOME_KEY}
    depends_on:
      - mongo
    networks:
      - node_app

  mongo:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - node_app
    ports:
      - 27017:27017

volumes:
  mongo_data:

networks:
  node_app:
