export const GAME_CODE_LENGTH = 5;

export const MAX_CHEFS = 8;
export const MIN_CHEFS = 3;

export const MIN_GAME_PASSWORD_LENGTH = 3;
export const MAX_GAME_PASSWORD_LENGTH = 30;

export const MIN_GAME_NAME_LENGTH = 2;
export const MAX_GAME_NAME_LENGTH = 255;

export const MIN_USER_NAME_LENGTH = 2;
export const MAX_USER_NAME_LENGTH = 255;

export const MAX_GAME_AGE_WITHOUT_ACTIVITY_IN_MINUTES = 60;

export const MIN_PASSWORD_LENGTH = 8;
export const MAX_PASSWORD_LENGTH = 255;

export const MIN_MESSAGE_LENGTH = 2;
export const MAX_MESSAGE_LENGTH = 512;

export const MULTILINGUAL_STRING_REGEX = /^[\s\p{N}\p{L}_-]+$/u;

export const MAX_HAND_SIZE = 4;
export const CHILI_PER_HAND = 1;
export const ROUNDS_TO_WIN = 2;

export const NONE = -1;

export default {
  CHILI_PER_HAND,
  GAME_CODE_LENGTH,
  MAX_CHEFS,
  MIN_CHEFS,
  MAX_GAME_PASSWORD_LENGTH,
  MIN_GAME_PASSWORD_LENGTH,
  MAX_GAME_NAME_LENGTH,
  MIN_GAME_NAME_LENGTH,
  MAX_HAND_SIZE,
  MAX_MESSAGE_LENGTH,
  MIN_MESSAGE_LENGTH,
  MAX_USER_NAME_LENGTH,
  MIN_USER_NAME_LENGTH,
  MAX_GAME_AGE_WITHOUT_ACTIVITY_IN_MINUTES,
  MAX_PASSWORD_LENGTH,
  MIN_PASSWORD_LENGTH,
  MULTILINGUAL_STRING_REGEX,
  ROUNDS_TO_WIN,
  NONE: NONE,
};
