export const GAME_CODE_LENGTH = 5;
export const MAX_CHEFS = 8;
export const MIN_CHEFS = 3;
export const MIN_GAME_PASSWORD_LENGTH = 3;
export const MAX_GAME_PASSWORD_LENGTH = 30;
export const MIN_GAME_NAME_LENGTH = 2;
export const MAX_GAME_NAME_LENGTH = 255;
export const MIN_USER_NAME_LENGTH = 2;
export const MAX_USER_NAME_LENGTH = 255;
export const MAX_GAME_AGE_WITHOUT_ACTIVITY_IN_MINUTES = 60;

export const MIN_PASSWORD_LENGTH = 8;
export const MAX_PASSWORD_LENGTH = 255;

export default {
  GAME_CODE_LENGTH,
  MAX_CHEFS,
  MIN_CHEFS,
  MIN_GAME_PASSWORD_LENGTH,
  MAX_GAME_PASSWORD_LENGTH,
  MIN_GAME_NAME_LENGTH,
  MAX_GAME_NAME_LENGTH,
  MIN_USER_NAME_LENGTH,
  MAX_USER_NAME_LENGTH,
  MAX_GAME_AGE_WITHOUT_ACTIVITY_IN_MINUTES,
  MIN_PASSWORD_LENGTH,
  MAX_PASSWORD_LENGTH,
};
